INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('White', 'Ecru', 'fafafa', 'white');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('White', '2', 'fafafa', 'white');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('Ecru', '387', 'f5f0ec', 'ecru');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('14', '1043', 'd0fbb2', 'apple green pale');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('14', '253', 'd0fbb2', 'apple green pale');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('51', '1220', 'cf5232', 'variegated burnt orange');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('52', '1209', '8c7ab6', 'variegated violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('57', '1203', 'e54a5a', 'variegated red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('69', '1218', 'c48c73', 'variegated terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('90', '1217', 'e6bf4a', 'variegated yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('92', '1215', 'c5ce95', 'variegated avocado');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('94', '1209', 'b5c385', 'variegated khaki green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('99', '1213', 'bd6c7b', 'variegated mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('103', '1217', '426da2', 'variegated royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('105', '1203', 'a5765a', 'variegated tan/brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('106', '1218', 'f65b3c', 'variegated coral');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('107', '1203', 'd6527a', 'variegated carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('107', '1204', 'd6527a', 'variegated carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('111', '1218', 'bd8e22', 'variegated mustard');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('115', '1206', '82192a', 'variegated garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('121', '1210', '7bb4d6', 'variegated delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('125', '1213', '63b47c', 'variegated seafoam green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('150', '59', 'a8024a', 'ul vy dk dustry rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('151', '23', 'f3c1cd', 'vy lt dustry rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('152', '969', 'e09a93', 'md lt shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('153', '103', 'e3c6d5', 'vy lt violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('153', '95', 'e3c6d5', 'vy lt violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('154', '873', '552332', 'vy dk grape');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('155', '1030', '948db3', 'md dk blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('156', '118', 'a5b0d1', 'md lt blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('157', '120', 'b7c4e4', 'vy lt cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('158', '123', '403d6d', 'md vy dk cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('158', '178', '403d6d', 'md vy dk cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('159', '120', 'c1c9d9', 'lt gray blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('160', '175', '8293b3', 'md gray blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('161', '176', '5c6694', 'gray blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('162', '159', 'c7e2ef', 'ul vy lt blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('163', '877', '559a6e', 'md celadon green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('164', '240', 'b6d4a3', 'lt forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('165', '278', 'eff39d', 'vy lt moss green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('166', '280', 'ced129', 'md lt moss green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('167', '898', 'ac8d3e', 'vy dk yellow beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('168', '398', 'c7cdce', 'vy lt pewter');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('169', '849', '7f8887', 'lt pewter');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('208', '111', '805988', 'vy dk lavender');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('209', '109', 'a078a5', 'dk lavender');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('210', '108', 'c09bc0', 'md lavender');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('211', '342', 'e0c5e0', 'lt lavender');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('221', '897', '9a3d43', 'vy dk shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('223', '895', 'd58582', 'lt shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('224', '893', 'e9b1a8', 'vy lt shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('225', '1026', 'ffd5d5', 'ul vy lt shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('225', '892', 'ffd7ce', 'ul vy lt shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('300', '352', '6d2d00', 'vy dk mahogany');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('301', '1049', 'af5b2a', 'md mahogany');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('304', '1006', 'b31e32', 'md red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('307', '289', 'fee73d', 'lemon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('309', '42', 'c9344d', 'dk rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('310', '403', '000000', 'black');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('311', '148', '064055', 'md navy blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('312', '979', '2e597c', 'vy dk baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('315', '1019', '903e4e', 'md dk antique mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('316', '1017', 'b56f7c', 'md antique mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('317', '400', '575d61', 'pewter gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('318', '399', '9c9ca4', 'lt steel gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('319', '218', '236831', 'vy dkpistachio green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('320', '215', '75bb71', 'md pistachio green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('321', '19', 'c32a3c', 'red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('321', '47', 'c32a3c', 'red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('321', '9046', 'c32a3c', 'red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('322', '978', '467194', 'dk dark baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('326', '59', 'af3a4a', 'vy dk rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('327', '100', '551346', 'dk violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('333', '110', '604e87', 'vy dk blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('333', '119', '604e87', 'vy dk blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('334', '977', '5f8da9', 'md baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('335', '1014', 'd64a5f', 'rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('336', '150', '0f3251', 'navy blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('340', '118', 'a4a4c4', 'md blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('341', '117', 'b8bfdc', 'lt blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('347', '1025', 'bf2642', 'vy dk salmon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('349', '13', 'c72e33', 'dk coral');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('350', '11', 'd64542', 'md coral');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('351', '10', 'de605e', 'coral');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('352', '9', 'ea8079', 'lt coral');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('353', '6', 'f2a898', 'peach');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('355', '1014', 'a5463c', 'dk terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('355', '884', 'a5463c', 'dk terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('356', '5975', 'd37863', 'md terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('367', '217', '4b924b', 'dk pistachio green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('368', '214', 'aad99f', 'lt pistachio green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('369', '1043', 'd2ebc5', 'vy lt pistachio green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('370', '855', 'ae9b54', 'md mustard');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('371', '854', 'b7a765', 'mustard');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('372', '853', 'c1ba7e', 'lt mustard');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('400', '351', '8c410f', 'dk mahogany');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('402', '1047', 'f7a170', 'vy lt mahogany');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('407', '914', 'bb8871', 'dk desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('413', '236', '3e4144', 'dk pewter gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('414', '235', '7c7c84', 'dk steel gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('414', '815', '7c7c84', 'dk steel gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('415', '398', 'bfbfc3', 'pearl gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('420', '374', '9a7b33', 'dk hazelnut brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('422', '372', 'd5b067', 'lt hazelnut brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('422', '943', 'd5b067', 'lt hazelnut brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('433', '357', '79511a', 'md brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('433', '358', '79511a', 'md brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('434', '310', '8c602a', 'lt brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('435', '1046', 'a0743e', 'vy lt brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('435', '365', 'a0743e', 'vy lt brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('435', '369', 'a0743e', 'vy lt brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('436', '1045', 'b58c53', 'tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('437', '362', 'c99f6a', 'lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('437', '368', 'c99f6a', 'lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('444', '290', 'fac800', 'dk lemon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('444', '291', 'fac800', 'dk lemon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('445', '288', 'fff983', 'lt lemon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('445', '802', 'fff983', 'lt lemon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('451', '233', '7c696d', 'dk shell gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('452', '232', 'ae9aa4', 'md shell gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('452', '676', 'ae9aa4', 'md shell gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('453', '231', 'd1c3cf', 'lt shell gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('469', '267', '819442', 'avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('470', '267', '9ead57', 'lt avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('471', '265', 'b9c572', 'vy lt avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('471', '266', 'b9c572', 'vy lt avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('472', '253', 'd5e191', 'ul lt avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('472', '254', 'd5e191', 'ul lt avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('498', '1005', 'a4132b', 'dk red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('498', '799', 'a4132b', 'dk red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('500', '683', '055538', 'vy dk blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('500', '879', '055538', 'vy dk blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('501', '878', '3d7654', 'dk blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('502', '221', '598d6e', 'blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('502', '877', '598d6e', 'blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('503', '876', '8ab5a0', 'md blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('504', '1042', 'b2d4bd', 'vy lt blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('504', '213', 'b2d4bd', 'vy lt blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('505', '210', '328060', 'jade green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('517', '162', '2e7288', 'dk wedgewood');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('518', '1039', '4d91a4', 'lt wedgewood');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('519', '1038', '6fb1c1', 'sky blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('520', '862', '42612b', 'dk fern green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('522', '860', '819569', 'fern green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('523', '859', 'b3be95', 'lt fern green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('524', '858', 'c1caa7', 'vy lt fern green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('535', '401', '555545', 'vy lt ash gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('543', '276', 'eaded3', 'ul vy lt beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('543', '933', 'eaded3', 'ul vy lt beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('550', '101', '4a133f', 'vy dk violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('550', '102', '4a133f', 'vy dk violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('552', '99', '793666', 'md violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('553', '92', 'a16089', 'violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('553', '98', 'a16089', 'violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('554', '96', 'd8aec7', 'lt violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('554', '97', 'd8aec7', 'lt violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('561', '212', '2b6843', 'vy dk jade');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('562', '210', '519468', 'md jade');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('562', '216', '519468', 'md jade');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('563', '208', '8cd2a8', 'lt jade');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('564', '206', 'b5e1be', 'vy lt jade');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('580', '281', '667913', 'dk moss green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('580', '817', '667913', 'dk moss green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('581', '280', '8ba136', 'moss green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('597', '1064', '57a2b1', 'turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('598', '1062', '82c1cd', 'lt turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('600', '59', 'd30b61', 'vy dk cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('601', '57', 'de2271', 'dk cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('602', '57', 'e64281', 'md cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('602', '63', 'e64281', 'md cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('603', '55', 'ee6195', 'cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('603', '62', 'ee6195', 'cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('604', '55', 'f784aa', 'lt cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('605', '1094', 'ffaac5', 'vy lt cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('605', '74', 'ffaac5', 'vy lt cranberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('606', '334', 'fd340c', 'bright orange-red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('606', '335', 'fd340c', 'bright orange-red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('608', '332', 'fd552f', 'bright orange');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('610', '889', '6f6641', 'dk drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('611', '354', '847a57', 'drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('611', '678', '847a57', 'drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('611', '898', '847a57', 'drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('612', '832', 'a29670', 'lt drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('613', '831', 'd4c7a8', 'vy lt drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('613', '956', 'd4c7a8', 'vy lt drab brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('632', '936', '936148', 'ul vy dk desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('640', '903', '918463', 'vy dk beige gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('642', '392', 'b8ad92', 'dk beige gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('644', '830', 'ddd3bc', 'md beige gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('645', '273', '515542', 'vy dk beaver gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('646', '8581', '707864', 'dk beaver gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('647', '1040', '959884', 'md beaver gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('648', '900', 'bcc0a8', 'lt beaver gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('666', '46', 'd90028', 'bright red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('676', '891', 'eeca70', 'lt old gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('677', '886', 'f4e7b4', 'vy lt old gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('680', '901', 'c8a027', 'dk old gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('699', '923', '005922', 'green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('700', '211', '07711a', 'bright green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('700', '228', '07711a', 'bright green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('701', '227', '1c8817', 'lt green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('702', '225', '46a42e', 'kelly green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('702', '226', '46a42e', 'kelly green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('702', '239', '46a42e', 'kelly green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('703', '238', '7ab146', 'chartreuse');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('704', '237', 'aeda62', 'bright chartreuse');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('704', '256', 'aeda62', 'bright chartreuse');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('712', '926', 'fff8e5', 'cream');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('718', '88', 'b73275', 'plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('720', '326', 'ef6a41', 'dk orange spice');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('721', '324', 'f37c51', 'md orange spice');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('721', '925', 'f37c51', 'md orange spice');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('722', '323', 'f79168', 'lt orange spice');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('725', '305', 'f7cc41', 'md lt topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('726', '295', 'f7dd68', 'lt topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('727', '293', 'f6e990', 'vy lt topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('728', '305', 'efc11a', 'topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('729', '820', 'e3b344', 'md old gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('729', '890', 'e3b344', 'md old gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('730', '845', '706c21', 'vy dk olive green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('731', '924', '989239', 'dk olive green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('732', '281', '989239', 'olive green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('733', '280', 'c0ba61', 'md olive green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('734', '279', 'd4ce75', 'lt olive green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('738', '361', 'ddb689', 'vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('738', '366', 'ddb689', 'vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('738', '367', 'ddb689', 'vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('738', '942', 'ddb689', 'vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('739', '276', 'f2d3a8', 'ul vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('739', '387', 'f2d3a8', 'ul vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('739', '885', 'f2d3a8', 'ul vy lt tan');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('740', '316', 'fa8500', 'tangerine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('741', '304', 'ff9d25', 'md tangerine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('741', '314', 'ff9d25', 'md tangerine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('742', '303', 'ffbc50', 'lt tangerine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('743', '301', 'ffe48b', 'pale yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('743', '302', 'ffdd64', 'md yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('744', '301', 'ffe48b', 'pale yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('745', '300', 'fff1b2', 'lt pale yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('746', '275', 'ffffe1', 'off white');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('747', '158', 'd3fff9', 'vy lt sky blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('754', '1012', 'f6c4b7', 'lt peach');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('758', '868', 'eda394', 'vy lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('758', '882', 'eda394', 'vy lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('758', '9575', 'eda394', 'vy lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('760', '1022', 'e6858f', 'salmon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('761', '1021', 'f2acac', 'lt salmon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('762', '234', 'e2e2e7', 'vy lt pearl gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('772', '259', 'e4feb0', 'vy lt yellow green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('772', '264', 'e4feb0', 'vy lt yellow green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('775', '128', 'd7ebf2', 'vy lt baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('776', '24', 'f3949f', 'md pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('777', '65', '810b28', 'vy dk Raspberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('778', '968', 'ddadb6', 'vy lt antique mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('779', '380', '604944', 'dk cocoa');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('780', '309', 'af5e00', 'ul vy dk topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('780', '370', 'af5e00', 'ul vy dk topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('781', '308', 'c77e00', 'vy dk topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('782', '307', 'c77e00', 'dk topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('783', '306', 'da9605', 'md topaz');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('791', '123', '363562', 'vy dk cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('791', '178', '363562', 'vy dk cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('792', '177', '4b497d', 'dk cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('792', '941', '4b497d', 'dk cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('793', '176', '7784af', 'md cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('794', '121', '8e9dc6', 'lt cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('794', '175', '8e9dc6', 'lt cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('796', '133', '0f2075', 'dk royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('797', '132', '223f88', 'royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('797', '139', '223f88', 'royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('797', '143', '223f88', 'royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('797', '147', '223f88', 'royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('798', '131', '3e5ea0', 'dk delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('798', '137', '3e5ea0', 'dk delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('798', '142', '3e5ea0', 'dk delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('798', '146', '3e5ea0', 'dk delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('799', '136', '5b81b5', 'md delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('799', '145', '5b81b5', 'md delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('800', '144', 'adcbe1', 'pale delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('801', '359', '653d0f', 'dk coffee brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('803', '149', '1e4669', 'ul vy dk baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('806', '169', '3d839f', 'dk peacock blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('807', '168', '5f9ea5', 'peacock blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('809', '121', '82a8c9', 'delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('809', '130', '82a8c9', 'delft blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('813', '161', '7eacc9', 'lt blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('814', '45', '79001c', 'dk garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('815', '22', '840720', 'md garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('815', '43', '840720', 'md garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('815', '44', '840720', 'md garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('816', '1005', '940b24', 'garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('816', '20', '940b24', 'garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('817', '13', 'bf1a23', 'vy dk coral red');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('818', '73', 'ffcece', 'baby pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('819', '271', 'ffe1e1', 'lt baby pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('820', '134', '000861', 'vy dk royal blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('822', '390', 'f3ecdc', 'lt beige gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('823', '127', '071f3a', 'dk navy blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('823', '152', '071f3a', 'dk navy blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('824', '164', '224271', 'vy dk blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('824', '940', '224271', 'vy dk blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('825', '162', '3a628c', 'dk blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('826', '161', '5785ad', 'md blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('827', '160', 'acd4e9', 'vy lt blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('828', '9159', 'b9e1e9', 'ul vy very lt blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('828', '975', 'b9e1e9', 'ul vy very lt blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('829', '906', '694f00', 'vy dk golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('830', '277', '766400', 'dk golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('831', '277', '928030', 'md golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('832', '907', 'a89234', 'golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('833', '907', 'ccba60', 'lt golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('834', '874', 'd5c77f', 'vy lt golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('834', '945', 'd5c77f', 'vy lt golden olive');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('838', '381', '523516', 'vy dk beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('839', '1086', '6a4726', 'dk beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('840', '1084', '967954', 'md beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('841', '1082', 'b39a7d', 'lt beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('842', '1080', 'd9c2a8', 'vy lt beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('842', '376', 'd9c2a8', 'vy lt beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('842', '388', 'd9c2a8', 'vy lt beige brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('844', '1041', '31372d', 'ul dk beaver gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('869', '375', '745e27', 'vy dk hazelnut brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('869', '944', '745e27', 'vy dk hazelnut brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('890', '218', '144b26', 'ul dk pistachio green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('891', '29', 'f32d3e', 'dk carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('891', '35', 'f32d3e', 'dk carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('892', '33', 'f75172', 'md carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('893', '27', 'fb7493', 'lt carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('893', '41', 'fb7493', 'lt carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('894', '26', 'ff9bb2', 'vy lt carnation');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('895', '1044', '1b5100', 'vy dk hunter green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('898', '360', '512d07', 'vy dk coffee brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('899', '52', 'e2697b', 'md rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('900', '333', 'db3700', 'dk burnt orange');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('902', '22', '6d1a2b', 'vy dk garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('902', '72', '6d1a2b', 'vy dk garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('902', '897', '6d1a2b', 'vy dk garnet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('904', '258', '2f6800', 'vy dk parrot green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('905', '257', '568f2e', 'dk parrot green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('906', '256', '89c53a', 'md parrot green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('907', '255', 'c6e560', 'lt parrot green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('909', '230', '0b7c38', 'vy dk emerald green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('909', '923', '0b7c38', 'vy dk emerald green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('910', '229', '1e9044', 'dk emerald green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('911', '205', '36a459', 'md emerald green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('912', '209', '53bd6a', 'lt emerald green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('913', '204', '76d185', 'md nile green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('915', '1029', '90004f', 'dk plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('917', '78', 'a4175d', 'md plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('917', '89', 'a4175d', 'md plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('917', '94', 'a4175d', 'md plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('918', '341', 'a02500', 'dk red copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('919', '340', 'bb3a0f', 'red copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('920', '1004', 'cf501e', 'md copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('920', '339', 'cf501e', 'md copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('920', '884', 'cf501e', 'md copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('921', '1003', 'e26132', 'copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('922', '1003', 'ec9163', 'lt copper');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('924', '816', '166059', 'vy dk gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('924', '851', '166059', 'vy dk gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('926', '850', '79a296', 'md gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('927', '837', 'a0bebe', 'lt gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('927', '848', 'a0bebe', 'lt gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('928', '274', 'c2d4d4', 'vy lt gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('930', '1035', '316274', 'dk antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('930', '840', '316274', 'dk antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('930', '922', '316274', 'dk antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('931', '1034', '46728c', 'md antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('931', '781', '46728c', 'md antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('931', '921', '46728c', 'md antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('932', '1033', '80a3ba', 'lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('932', '920', '80a3ba', 'lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('934', '862', '314615', 'black avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('935', '861', '3b4d0f', 'dk avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('936', '269', '52651a', 'vy dk avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('937', '268', '697c2e', 'md avocado green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('938', '1088', '3e2200', 'ul dk coffee brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('938', '381', '3e2200', 'ul dk coffee brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('939', '152', '001326', 'vy dk navy blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('943', '188', '39ac78', 'md aquamarine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('945', '366', 'ffc9ae', 'tawny');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('945', '881', 'ffc9ae', 'tawny');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('946', '332', 'de4600', 'md burnt orange');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('947', '330', 'e66007', 'burnt orange');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('948', '1011', 'fddcc5', 'vy lt peach');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('950', '4146', 'ebc8b3', 'lt desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('951', '1010', 'ffddc6', 'lt tawny');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('951', '880', 'ffddc6', 'lt tawny');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('954', '203', '99e5a6', 'nile green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('955', '206', 'c6ffca', 'lt nile green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('956', '28', 'fb5c84', 'geranium');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('956', '38', 'fb5c84', 'geranium');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('956', '40', 'fb5c84', 'geranium');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('956', '54', 'fb5c84', 'geranium');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('957', '50', 'ff9bba', 'pale geranium');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('958', '187', '5bc39d', 'dk seagreen');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('959', '185', '85d5b6', 'md seagreen');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('959', '186', '85d5b6', 'md seagreen');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('961', '76', 'da627c', 'dk dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('962', '75', 'dd818f', 'md dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('963', '23', 'ffced7', 'ul vy lt dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('963', '48', 'ffced7', 'ul vy lt dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('963', '73', 'ffced7', 'ul vy lt dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('964', '1092', 'b4f2df', 'lt seagreen');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('966', '206', 'a2d5ae', 'md baby green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('967', '1012', 'ffc9b4', 'vy lt apricot');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('970', '316', 'f7860e', 'lt pumpkin');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('971', '316', 'fa8500', 'pumpkin');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('972', '298', 'f7be12', 'deep canary');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('973', '297', 'fadd00', 'bright canary');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('975', '355', '8e4c12', 'dk golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('975', '371', '8e4c12', 'dk golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('976', '1001', 'cb8234', 'md golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('976', '803', 'cb8234', 'md golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('977', '1002', 'db9851', 'lt golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('977', '363', 'db9851', 'lt golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('986', '246', '2b671f', 'vy dk forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('987', '244', '408128', 'dk forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('987', '245', '408128', 'dk forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('988', '243', '68a046', 'md forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('989', '241', '92bf68', 'forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('989', '242', '92bf68', 'forest green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('991', '1076', '0b6d4c', 'dk aquamarine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('992', '1070', '7ecdaf', 'vy lt aquamarine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('992', '1072', '4aac88', 'vy lt aquamarine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('993', '185', '7ecdaf', 'vy lt aquamarine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('995', '410', '016ea5', 'dk electric blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('996', '433', '13bcde', 'md electric blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3011', '846', '6e783b', 'dk khaki green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3012', '843', '939857', 'md khaki green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3012', '844', '939857', 'md khaki green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3013', '842', 'b7b77e', 'lt khaki green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3021', '905', '44452a', 'vy dk brown gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3022', '8581', '84835c', 'md brown gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3023', '1040', 'aeab8a', 'lt brown gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3024', '397', 'd7d7c3', 'vy lt brown gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3031', '905', '473727', 'vy dk mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3032', '903', 'ae9d78', 'md mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3033', '391', 'e0d4c3', 'vy lt mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3041', '871', '937580', 'md antique violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3042', '870', 'b499a4', 'lt antique violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3045', '888', 'c5ad66', 'dk yellow beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3046', '887', 'd9cda3', 'md yellow beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3047', '852', 'e7e1b8', 'lt yellow beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3051', '681', '516132', 'dk green gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3052', '262', '798855', 'md green gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3053', '261', 'a4b583', 'green gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3064', '347', 'ca9073', 'desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3064', '883', 'ca9073', 'desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3072', '847', 'e3e7d9', 'vy lt beaver gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3078', '292', 'faf6b7', 'vy lt golden yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3325', '129', 'a6c3d9', 'lt baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3326', '36', 'f3949f', 'lt rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3328', '1024', 'ce3f54', 'dk salmon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3340', '329', 'fa8155', 'md apricot');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3341', '328', 'ff9774', 'apricot');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3345', '268', '2f6913', 'dk hunter green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3346', '267', '4b8835', 'hunter green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3346', '268', '4b8835', 'hunter green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3347', '266', '76a451', 'md yellow green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3348', '264', 'ceeb90', 'lt yellow green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3348', '842', 'ceeb90', 'lt yellow green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3350', '59', 'b84263', 'ul dk dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3350', '65', 'b84263', 'ul dk dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3354', '74', 'eea1b2', 'lt dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3362', '263', '4a6332', 'dk pine green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3363', '262', '6e8d58', 'md pine green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3364', '260', '9db275', 'pine green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3371', '382', '3a2723', 'black brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3607', '87', 'd25292', 'lt plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3608', '86', 'e67dac', 'vy lt plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3609', '85', 'ffaacf', 'ul lt plum');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3685', '1028', '851531', 'vy dk mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3685', '70', '851531', 'vy dk mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3687', '68', 'c65375', 'mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3687', '77', 'c65375', 'mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3687', '79', 'c65375', 'mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3687', '970', 'c65375', 'mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3688', '60', 'e890ac', 'md mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3688', '66', 'e890ac', 'md mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3689', '49', 'fdbace', 'lt mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3705', '35', 'f75156', 'dk melon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3706', '33', 'ff7f8c', 'md melon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3708', '31', 'ffa2b0', 'lt melon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3712', '1023', 'da6270', 'md salmon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3713', '1020', 'ffd5d5', 'vy lt salmon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3716', '25', 'f6a7b4', 'vy lt dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3721', '896', 'ac4a52', 'dk shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3722', '1027', 'c16363', 'md shell pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3726', '1018', 'a45561', 'dk antique mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3727', '1016', 'c98c97', 'lt antique mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3731', '76', 'd96280', 'vy dk dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3733', '75', 'e78197', 'dusty rose');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3740', '872', '765561', 'dk antique violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3740', '873', '765561', 'dk antique violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3743', '869', 'd3c6cf', 'vy lt antique violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3746', '1030', '746896', 'dk blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3747', '120', 'cdd2ea', 'vy lt blue violet');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3750', '1036', '1b3e49', 'vy dk antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3752', '1032', '9ab3cd', 'vy lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3752', '274', '9ab3cd', 'vy lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3752', '343', '9ab3cd', 'vy lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3752', '976', '9ab3cd', 'vy lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3753', '1031', 'cddbe8', 'ul vy lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3753', '1096', 'cddbe8', 'ul vy lt antique blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3755', '140', '83a4c1', 'baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3755', '939', '83a4c1', 'baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3756', '1037', 'e7f9f9', 'ul vy lt baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3760', '169', '3d839f', 'md wedgewood');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3761', '928', '9dd5dd', 'lt sky blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3765', '170', '17616d', 'vy dk peacock blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3766', '167', '9acdcd', 'lt peacock blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3768', '779', '528779', 'dk gray green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3770', '1009', 'fff3e1', 'vy lt tawny');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3771', '336', 'f3b5a2', 'ul vy lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3772', '1007', 'aa7959', 'vy dk desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3772', '679', 'aa7959', 'vy dk desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3772', '772', 'aa7959', 'vy dk desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3773', '1008', 'bb8871', 'md desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3773', '1009', 'bb8871', 'md desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3774', '778', 'f1dbd0', 'vy lt desert sand');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3776', '1048', 'ce7535', 'lt mahogany');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3777', '1015', '8e3230', 'vy dk terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3778', '1013', 'da8e7f', 'lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3778', '337', 'da8e7f', 'lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3778', '338', 'da8e7f', 'lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3779', '1012', 'efbdba', 'ul vy lt terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3781', '1050', '574d2a', 'dk mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3781', '904', '574d2a', 'dk mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3782', '899', 'cabca3', 'lt mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3787', '273', '656040', 'dk brown gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3790', '393', '776847', 'ul dk beige gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3799', '236', '2b2c2f', 'vy dk pewter gray');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3801', '1098', 'f03646', 'vy dk melon');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3802', '1019', '7c2a40', 'vy dk antique mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3803', '69', 'a83255', 'dk mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3803', '972', 'a83255', 'dk mauve');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3804', '63', 'e6367c', 'dk cyclamen pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3805', '62', 'f34188', 'cyclamen pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3806', '62', 'fd75a9', 'lt cyclamen pink');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3807', '122', '5b648f', 'cornflower blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3808', '1068', '0b525d', 'ul vy dk turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3808', '675', '0b525d', 'ul vy dk turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3809', '1066', '1e6a79', 'vy dk turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3810', '1066', '3a8594', 'dk turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3811', '1060', 'b4e0e9', 'vy lt turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3812', '188', '1c925f', 'vy dk seagreen');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3813', '219', 'b2d4bd', 'lt blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3813', '875', 'b2d4bd', 'lt blue green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3814', '1074', '228c69', 'aquamarine');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3815', '877', '397a59', 'dk celadon green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3816', '876', '78b48a', 'celadon green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3817', '875', 'aad9ba', 'lt celadon green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3818', '224', '00692d', 'ul vy dk emerald greene');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3818', '923', '00692d', 'ul vy dk emerald greene');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3819', '278', 'e0e762', 'lt moss green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3820', '306', 'e2b735', 'dk straw');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3821', '305', 'f2cd49', 'straw');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3822', '295', 'f2df70', 'lt straw');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3823', '386', 'fefbce', 'ul pale yellow');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3824', '8', 'ffb496', 'lt apricot');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3825', '323', 'fdb78e', 'pale pumpkin');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3825', '891', 'fdb78e', 'pale pumpkin');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3826', '1049', 'b66e2a', 'golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3826', '349', 'b66e2a', 'golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3827', '311', 'f7b670', 'pale golden brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3828', '373', 'b2913c', 'hazelnut brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3829', '901', 'a67d04', 'vy dk old gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3830', '5975', 'c35a4c', 'terra cotta');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3831', '42', 'b22b54', 'dk raspberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3831', '59', 'b22b54', 'dk raspberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3832', '39', 'e0577e', 'md raspberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3833', '76', 'eb6d84', 'lt raspberry');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3834', '100', '70365b', 'dk grape');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3835', '98', '915e81', 'md grape');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3836', '90', 'b78da7', 'lt grape');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3837', '100', '69396c', 'ul dk lavender');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3837', '112', '69396c', 'ul dk lavender');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3838', '137', '5d6f9d', 'dk lavender blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3839', '176', '798fb3', 'md lavender blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3840', '117', 'a7b2c5', 'lt lavender blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3841', '9159', 'bfdbe7', 'pale baby blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3842', '164', '17566d', 'dk wedgwood');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3843', '1089', '0493be', 'electric blue');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3844', '410', '099d89', 'dk bright turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3845', '1089', '04baae', 'md bright turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3846', '1090', '44dec7', 'lt bright turquoise');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3847', '1076', '2b6f51', 'dk teal green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3848', '1074', '3c8b6e', 'md teal green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3850', '189', '0f9161', 'dk bright green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3851', '187', '66bf9d', 'lt bright green');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3852', '306', 'd2a021', 'vy dk straw');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3853', '1003', 'e58632', 'dk autumn gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3854', '313', 'f9b460', 'md autumn gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3855', '311', 'f9da8c', 'lt autumn gold');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3856', '1010', 'f5c3a9', 'ul vy lt mahogany');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3858', '1007', '93483e', 'md rosewood');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3859', '914', 'b88778', 'lt rosewood');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3860', '379', '8f6d65', 'cocoa');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3861', '378', 'a4857e', 'lt cocoa');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3862', '358', '8c6f4e', 'dk mocha beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3863', '379', 'a88764', 'md mocha beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3863', '677', 'a88764', 'md mocha beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3864', '376', 'cbb69c', 'lt mocha beige');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3865', '2', 'f9f7f1', 'winter white');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('3866', '926', 'f8f2e9', 'ul vy lt mocha brown');
INSERT OR IGNORE INTO dmc_to_anchor (dmc, anchor, hex, fname) VALUES ('B5200', 'Ecru', 'fafafa', 'snow white');
